#
# Continuous integration for project.
#

image: python:3.8

test-python-3-7:
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37

test-python-3-8:
  image: python:3.8
  script:
    - pip install tox
    - tox -e type -e lint -e py38
run:
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl

# Compile and publish documentation for the project.
pages:
  script:
    - pip install sphinx sphinx-rtd-theme recommonmark
    - cd docs ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - main
