#!/usr/bin/env python3

from ecmwf_pipeline.download_pipeline import cli
import pkg_resources

if __name__ == '__main__':
    cli(['--setup_file', pkg_resources.resource_filename('ecmwf_pipeline', 'setup.py')])
