apiVersion: batch/v1
kind: Job
metadata:
  name: downloader-with-ttl
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: downloader
        image: XXXXXXXXXXXX
        imagePullPolicy: Always
        command: []
        resources:
          requests:
            cpu: "1000m"                  # CPU: 1 vCPU
            memory: "2Gi"                 # RAM: 2 GiB
            ephemeral-storage: "100Gi"    # Storage: 100 GiB
        volumeMounts:
        - name: data
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: data
        emptyDir:
          sizeLimit: 100Gi