#!/usr/bin/env python3
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
import subprocess
import sys

import weather_mv

if __name__ == '__main__':
    logging.getLogger().setLevel(logging.INFO)

    site_pkg = weather_mv.__path__[0]

    try:
        from loader_pipeline import cli
    except ImportError:
        # Install the subpackage.
        subprocess.check_call(f'{sys.executable} -m pip -q install -e {site_pkg}'.split())

        # Re-load sys.path
        import site
        from importlib import reload
        reload(site)

        # Re-attempt import. If this fails, the user probably has an older version of
        # the package already installed on their machine that breaks this process.
        # If that's the case, it's best to start from a clean virtual environment.
        try:
            from loader_pipeline import cli
        except ImportError as e:
            raise ImportError('please re-install package in a clean python environment.') from e

    cli()
