name: weather-dl-v2-downloader
channels:
  - conda-forge
dependencies:
  - python=3.10
  - google-cloud-sdk=410.0.0
  - aria2=1.36.0
  - pip=22.3
  - pip:
    - firebase-admin
    - google-cloud-storage
    - google-cloud-pubsub
    - kubernetes
    - redis
