apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pubsub-subscriber
spec:
  selector:
    matchLabels:
      app: redis-pubsub-subscriber
  template:
    metadata:
      labels:
        app: redis-pubsub-subscriber
    spec:
      containers:
      - name: subscriber
        image: XXXXXXXXXXX
        imagePullPolicy: Always
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-pubsub-subscriber
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-pubsub-subscriber
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-pubsub-subscriber
---