#!/usr/bin/env python3

from netcdf_loader.loader_pipeline import cli
import pkg_resources

if __name__ == '__main__':
    cli(['--setup_file', pkg_resources.resource_filename('netcdf_loader', 'setup.py')])

